services:
  - type: web
    name: enterprise-procurement-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_4MDzu0iQmegq@ep-little-dew-ae953rdn-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: FRONTEND_URL
        sync: false

